SELECT *
FROM employees;

SELECT employee_name AS NAME
FROM employees;

SELECT salary AS monthly_salary
FROM employees;

SELECT *
FROM employees
ORDER BY salary ASC;

SELECT *
FROM employees;

SELECT CURRENT_DATE;

SELECT CURRENT_TIME;

SELECT CURRENT_TIMESTAMP;

SELECT NOW();

SELECT EXTRACT(YEAR FROM DATE '2002-01-05');

SELECT EXTRACT (MONTH FROM DATE '2002-01-05');

SELECT EXTRACT (DAY FROM DATE '2002-01-05');

SELECT EXTRACT(HOURS FROM NOW());

SELECT EXTRACT (MINUTES FROM NOW());

SELECT EXTRACT (SECONDS FROM NOW());

SELECT EXTRACT (QUARTER FROM NOW());

SELECT NOW();

SELECT EXTRACT (WEEK FROM CURRENT_DATE);

SELECT EXTRACT (DOW FROM CURRENT_DATE);

SELECT EXTRACT(DOY FROM CURRENT_DATE);

SELECT DATE_PART ('year', current_date);

SELECT DATE_PART ('month', CURRENT_DATE);

SELECT DATE_PART ('day', CURRENT_DATE);

SELECT AGE('2026-07-04', '2002-01-05');

SELECT AGE(CURRENT_DATE, DATE '2002-01-05');

SELECT CURRENT_DATE - DATE '2002-01-05';

SELECT CURRENT_DATE + 10;

SELECT CURRENT_DATE - 10;

SELECT CURRENT_DATE + INTERVAL '5 days';

SELECT CURRENT_DATE - INTERVAL '5 DAYS';

SELECT CURRENT_DATE + INTERVAL '2 MONTHS';

SELECT CURRENT_DATE + INTERVAL '2 years' AS demo;

SELECT NOW() + INTERVAL ' 5 Hours';

SELECT NOW() + INTERVAL '2 years 1 month 2 days';

SELECT DATE_TRUNC('hours', NOW());

SELECT DATE_TRUNC('year', NOW());

SELECT DATE_TRUNC('day', NOW());

SELECT DATE_TRUNC('hour', NOW());

SELECT TO_CHAR(CURRENT_DATE, 'DD');

SELECT TO_CHAR(CURRENT_DATE, 'month');

SELECT TO_CHAR(CURRENT_DATE, 'YYYY');

SELECT TO_CHAR (CURRENT_DATE, 'DAY');

SELECT TO_CHAR (CURRENT_DATE, 'MM');

SELECT TO_CHAR (CURRENT_DATE, 'DD-MM-YYYY');

